Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\site-packages\jupyter_core\utils\__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 706, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\peter\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from myst_nb import glue

def smooth(x):
    n = len(x)
    result = np.zeros((n, n))
    for i in range(1, n-1):
        for j in range(1, n-1):
            result[i,j] = np.average(x[i-1:i+2,j-1:j+2])
    return result

def diffuse(x, d):
    n = len(x)
    result = np.zeros((n, n))
    for i in range(1, n-1):
        for j in range(1, n-1):
            total = np.sum(x[i-1:i+2,j-1:j+2]) - x[i,j]

            result[i,j] = x[i,j] + total * d - x[i,j] * 8 * d
    return result

n = 40
N = 4

grid = np.zeros((n, n))
grid[16:24,16:24] = 1

gs_kw = dict(width_ratios=[1, 1, 1, 1, 1, .2], wspace=0)
fig, axes = plt.subplots(1, N + 2, figsize=(9,1.5), gridspec_kw=gs_kw)
fig.subplots_adjust(wspace=0, hspace=0)

pcm = axes[0].imshow(grid, vmin=0, vmax=1)
axes[0].axis("off")
for i in range(N):
    for j in range(2 ** N):
        grid = diffuse(grid, 0.03)
        axes[i+1].imshow(grid, vmin=0, vmax=1)
        axes[i+1].axis("off")
axes[-1].axis("off")
cbar = fig.colorbar(pcm, ax = axes[-1], fraction=0.55, aspect=8)
cbar.set_label("Relative\nConcentration")

glue("diffusion", fig, display=False)








------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_7964\3995902574.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mfrom[0m [0mmyst_nb[0m [1;32mimport[0m [0mglue[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [1;32mdef[0m [0msmooth[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'numpy'

